### ISSUE TITLE
Include customer APIs in API-explorer

### ISSUE THREAD

**Issue by trycoon** [Alfresco/rest-api-explorer#46]
This is service is a very nice addition to the Alfresco suite making everyday development a lot easier, but it would be even better if the API that we as users create is also visualized in the API-explorer. When I develop a plattform-extension that contains a REST-API endpoint it would be nice if I could export a yaml-document to the API-explorer to include, or even better if the API-explorer could generate one self out of reflection of my classes. Currently I have to include Swagger to visualize our own APIs, which feels like double work now that the API-explorer is available.

**Comment by derekhulley** [comment]
This does seem like a useful addition; thank you for taking the time to highlight it.
Since the requirement is to visualize the default Alfresco APIs, I doubt that we'd have time to extend the API-explorer from our side.
If you find a way to do it, please contribute it back and we can incorporate it.
